# Generated by Django 4.1.5 on 2023-01-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
    ]
